### PR TITLE
feature: Jspsych

### PR DESCRIPTION
**Pull request by ericawright**
@phlsa @bwinton @jtg567

run 3 trials - at least one of each 2 options, with a random third one.
  - all three in random order

each trial has a random delay of 2,3, or 5s (it is possible that each trial end up with the same delay or all different etc.)

run a survey after each trial
- the survey has the data from the trial attached to it as well

currently logging the trial data after each trial for our convenience  (this will need to be removed before running actual trials)

### CODE REVIEW

**Comment by bwinton** [comment]
That was a fast merge…  I thought we might get a chance to comment on it first.  :)

**Comment by phlsa** [comment]
Sorry, I haven't really used Github in that way before... Do you have comments?

**Comment by bwinton** [comment]
I looked through it, but my main comment was to ask Erica to fade out the prototype before fading in the survey…  😉  As more of a data-person Josh might have comments about how many and which tests we're running.  (Like, I recommended three trials, one of each cohort, and a third random one, and three different times, but is that the right thing to do?  I have no idea! 🙂)

**Comment by jtg567** [comment]
@bwinton a good test of whether the number of trials is sufficient (as well as how effective the manipulation of the independent variables are) is to dogfood the experiment, look at a plot of the data, and ask the following Qs: Are averages for the different levels of the independent variable (in this case the 2 variants of animation and the 3 levels of duration) different? How wide are the error bars around the averages? If averages have wide, overlapping error bars (i.e. variances) they're typically narrowed by increasing the number of trials, increasing stability of averages. 

Ideally what you'll find - if the manipulations are psychologically effective - is averages that are not the same with variances that don't overlap. That's at least approaching "statistically significant effects". Rather than choose manipulations arbitrarily, I'd advise the number of levels and values of duration be chosen carefully after reviewing the related literature. I've updated my journal database subscription to have a look myself, but it seems like there's a lag between paying them and having my access info updated.

Are you asking participants to rate the duration of the animations open-endedly, or letting them choose from a discrete set of options?

**Comment by bwinton** [comment]
@jtg567: Discrete set of options; 1, 2, 3, 4, 5, 6, 7, or 8 seconds currently, but as ever, we're open to change them.  🙂

**Comment by jtg567** [comment]
If nothing that's better than if 2, 3, and 5 were the only options. My concern is that I'm intuitively not convinced that the two animations could be so different that people would reliably say one was an entire second faster/slower or more; rather, I'd reckon any reliable difference that's present to be less than a second. As such, you'd need to give people the ability to respond with that granularity - perhaps with a slider that changes a numeric text value when it is dragged continuously.

With this type of research it is extremely common to test a procedure on a smaller number of people and tweak it until measurements/manipulations are optimal. So, you may be best running 30-100 people with the current procedure and looking at the data before making further changes.

**Pull request merged**
